# Generated by Django 5.0.1 on 2024-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="placeholder.png", null=True, upload_to="article"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="intro",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="time_required_to_read",
            field=models.CharField(default="2 minutes", max_length=250),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
