# Generated by Django 5.0.1 on 2024-02-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_post_image_post_intro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
