# Generated by Django 5.0.1 on 2024-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_sub_title_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendingArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="placeholder.png",
                        null=True,
                        upload_to="article",
                    ),
                ),
                ("article_number", models.CharField(max_length=250)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "time_required_to_read",
                    models.CharField(default="2 Min Read", max_length=250),
                ),
                ("title", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="time_required_to_read",
            field=models.CharField(default="2 Min Read", max_length=250),
        ),
    ]
